dbms/fashionHub/apps/designer/urls.py
from unicodedata import name
from django.contrib.auth import views as auth_views
from django.urls import path
from . import views

urlpatterns = [
    path('become-designer/',views.become_designer,name='become_designer'),
    path('designer-admin/',views.designer_admin,name='designer_admin'),
    path('add-product/',views.add_product, name='add_product'),
    path('edit-designer/',views.edit_designer,name='edit_designer'),
    path('designers/',views.designers,name='designers'),
    path('<int:designer_id>/',views.designer,name='designer'),

    
]

dbms/fashionHub/fashionHub/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.core.urls')),
    path('designers/',include('apps.designer.urls')),
    path('cart/',include('apps.cart.urls')),
    path('customers/',include('apps.customer.urls')),
    path('',include('apps.product.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dbms/fashionHub/apps/designer/models.py
from django.db import models
from apps.core.models import User


# Create your models here.

class Designer(models.Model):
    name = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.OneToOneField(User, related_name='designer', on_delete=models.CASCADE)

    class Meta:
        ordering = ['name']


    def get_balance(self):
        items = self.items.filter(designer_paid = False, order__designers__in=[self.id])
        return sum((item.product.price * item.quantity) for item in items)

    def get_paid_amount(self):
        items = self.items.filter(designer_paid = True, order__designers__in=[self.id])
        return sum((item.product.price * item.quantity) for item in items)

dbms/fashionHub/apps/order/models.py
from django.db import models
from apps.product.models import Product
from apps.designer.models import Designer
from apps.customer.models import Customer

# Create your models here.

class Order(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    zipcode = models.CharField(max_length=255)
    place= models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    paid_amount = models.DecimalField(max_digits=9,decimal_places=2)
    designers = models.ManyToManyField(Designer, related_name='orders')
    customer = models.ForeignKey(Customer,on_delete=models.CASCADE, related_name='order' )

    class Mata:
        ordering = ['-created_at']

    def __str__(self):
        return self.first_name


class OrderItem(models.Model):
    order = models.ForeignKey(Order,related_name='items',on_delete=models.CASCADE)
    product = models.ForeignKey(Product,related_name='items',on_delete=models.CASCADE)
    designer = models.ForeignKey(Designer,related_name='items',on_delete=models.CASCADE)
    designer_paid = models.BooleanField(default=False)
    price = models.DecimalField(max_digits=9,decimal_places=2)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return '%s' % self.id

    def get_total_price(self):
        return self.price * self.quantity

dbms/fashionHub/apps/product/models.py
from unicodedata import category
from django.db import models
from io import BytesIO
from PIL import Image
from django.core.files import File
from apps.designer.models import Designer

# Create your models here.

class Category(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    ordering = models.IntegerField(default=0)

    class Meta:
        ordering = ['ordering']

    def __str__(self):
        return self.title

class Product(models.Model):
    category = models.ForeignKey(Category,related_name='products',on_delete=models.CASCADE)
    designer = models.ForeignKey(Designer,related_name='products',on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=9,decimal_places=2)
    date_added = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(upload_to='uploads/',blank=True,null=True)
    thumbnail = models.ImageField(upload_to='uploads/',blank=True,null=True)

    class Meta:
        ordering = ['-date_added']

    def __str__(self):
        return '%s' % self.id

    def get_thumbnail(self):
        if self.thumbnail:
            return self.thumbnail.url
        else:
            if self.image:
                self.thumbnail = self.make_thumbnail(self.image)
                self.save()

                return self.thumbnail.url
            else:
                return 'https://via.placeholder.com/240x180.jpg'
    
    def make_thumbnail(self, image, size=(300, 200)):
        img = Image.open(image)
        img.convert('RGB')
        img.thumbnail(size)

        thumb_io = BytesIO()
        img.save(thumb_io, 'JPEG', quality=85)

        thumbnail = File(thumb_io, name = image.name)

        return thumbnail

dbms/fashionHub/apps/cart/forms.py
from django import forms

class CheckoutForm(forms.Form):
    first_name = forms.CharField(max_length=255)
    last_name = forms.CharField(max_length=255)
    email = forms.EmailField(max_length=255)
    phone = forms.CharField(max_length=255)
    address = forms.CharField(max_length=255)
    zipcode = forms.CharField(max_length=255)
    place = forms.CharField(max_length=255)
    stripe_token = forms.CharField(max_length=255)

dbms/fashionHub/apps/designer/forms.py
from django.forms import ModelForm
from apps.product.models import Product

class Productform(ModelForm):
    class Meta:
        model = Product
        fields = ['category','image','title','description','price']

dbms/fashionHub/apps/designer/views.py
import imp
from wsgiref.util import request_uri
from colorama import Cursor
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from .models import Designer
from django.contrib.auth.decorators import login_required
from apps.product.models import Product
from .forms import Productform
from django.utils.text import slugify
from apps.product.models import Category
from apps.core.models import User
# Create your views here.



def become_designer(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            user = form.save()

            login(request,user)

            designer = Designer.objects.create(name=user.username, created_by=user)

            return redirect('frontpage')

    else:
        form = UserCreationForm()

    return render(request,'designer/become_designer.html',{'form': form})

@login_required
def designer_admin(request):
    designer = request.user.designer
    products = designer.products.all()
    orders = designer.orders.all()

    for order in orders:
        order.designer_amount = 0
        order.designer_paid_amount = 0
        order.fully_paid = True

        for item in order.items.all():
            if item.designer == request.user.designer:
                if item.designer_paid:
                    order.designer_paid_amount += item.get_total_price()
                else:
                    order.designer_amount += item.get_total_price()
                    order.fully_paid = False


    return render(request,'designer/designer_admin.html',{'designer':designer,'products':products, 'orders': orders})

@login_required
def add_product(request):
    if request.method == 'POST':
        form = Productform(request.POST, request.FILES)

        if form.is_valid():
            product = form.save(commit=False)
            product.designer = request.user.designer
            product.slug = slugify(product.title)
            product.save()

            return redirect('designer_admin')
    
    else:
        form = Productform()

    return render(request, 'designer/add_product.html',{'form':form})

@login_required
def edit_designer(request):
    designer = request.user.designer

    if request.method == 'POST':
        name = request.POST.get('name','')
        email = request.POST.get('email','')

        if name:
            designer.created_by.email = email
            designer.created_by.save()

            designer.name = name
            designer.save()

            return redirect('designer_admin')

    return render(request, 'designer/edit_designer.html',{'designer':designer})

from django.db import connection
cursor = connection.cursor()
def designers(request):
    #designers = Designer.objects.all()
  
    cursor.execute('call showAllDesigners')
    d = cursor.fetchall()
    designers = list(d)
    return render(request, 'designer/designers.html',{'designers':designers})
    

def designer(request, designer_id):
    designer = get_object_or_404(Designer, pk=designer_id)
    

    return render(request, 'designer/designer.html',{'designer':designer})

dbms/fashionHub/apps/designer/templates/designer/add_product.html
{% extends 'core/base.html' %}

{% block title %}Add Product| {% endblock %}

{% block content %}
<h1 class="title" style="text-align: center;">Add Product</h1>

<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}
    <p><label for="id_category">Category:</label> <select name="category" required id="id_category" style="margin-left: 30px;width: 40%;
        height: 40px;justify-content: center;
	display: flex;text-align: center;font-size:1.6em;">
        <option value="" selected>--select--</option>
      
        <option value="1">Gowns</option>
      
        <option value="2">Sarees</option>
      
        <option value="3">Kurtas</option>
      
        <option value="4">Tops &amp; T-Shirts</option>
      
        <option value="5">Jackets</option>
      
        <option value="6">Jeans</option>
      
        <option value="7">Suits &amp; Blazers</option>
      
        <option value="8">Trousers</option>
      
        <option value="9">Jumpsuits</option>
      
        <option value="10">Lehengas</option>
      
      </select></p>
    <p><label for="id_image">Image:</label> <input type="file" name="image" accept="image/*" id="id_image"></p>
    <p><label for="id_title">Title:</label> <input type="text" name="title" maxlength="255" required id="id_title"></p>
    <p><label for="id_description">Description:</label> <textarea name="description" cols="40" rows="10" id="id_description"style="margin-left: 30px;width: 40%;
        height: 150px;justify-content: center;
	display: flex;text-align: center;font-size:1.6em;">
    </textarea></p>
    <p><label for="id_price">Price:</label> <input type="number" name="price" step="0.01" required id="id_price"></p>

    <div class="field">
        <div class="control">
            <button class="button is-dark is-uppercase" style="width: 20%;
            height: 40px;
            margin-left: 120px;
            justify-content: center;
            display: block;
            color: #fff;
            background: #573b8a;
            font-size: 1em;
            font-weight: bold;
            margin-top: 20px;
            outline: none;
            border: none;
            border-radius: 5px;
            transition: .2s ease-in;
            cursor: pointer;">Submit</button>
        </div>
    </div>
</form>

{% endblock %}

dbms/fashionHub/apps/designer/templates/designer/become_designer.html
{% load static %}

<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />
        <title>Designer | FashionHub</title>

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
        <link rel="stylesheet" href="{% static 'styles/main.css' %}">
    
        <script src="{% static 'scripts/main.js' %}"></script>
    </head>

    <body >
        <nav class="navbar is-dark">
            <div class="navbar-brand">
                <a href="/" class="navbar-item"><strong>FashionHub</strong></a>
        
                <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="main-navbar">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            </div>
        
            <div class="navbar-menu" id="main-navbar">
                <div class="navbar-start">
                    <div class="navbar-item">
                        <form method="post" action="{% url 'search' %}">
                            {% csrf_token %}
                            <div class="field has-addons">
                                <div class="control">
                                    <input type="text" class="input" placeholder="Search..." name="query">
                                </div>
                                <div class="control">
                                    <button class="button is-dark is-uppercase">Search</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="navbar-end">
                    <a href="{% url 'designers' %}" class="navbar-item">Designers</a>
                    <a href="{% url 'contact' %}" class="navbar-item">Contact</a>

                   {% if request.user.is_authenticated %}
                   <a href="{% url 'logout' %}" class="navbar-item">logout</a>
                   <a href="{% url 'designer_admin' %}" class="navbar-item">{{user.first_name}}</a>
                   {% else %}
                    <a href="{% url 'designer_register' %}" class="navbar-item">SignUp</a>
                    <a href="{% url 'login' %}" class="navbar-item">SignIn</a>
                    {% endif %}
                    
                    
                   
                </div>
            </div>
        </nav>
        <div >
        <section class="section" >
            <div class="container">
                <img src="https://media.weddingsonly.in/blogger/285344f0a8d3daa65ebe1b72cbe75b4e/34d02c7c5d90464bb52d_sabyasachi-banner.jpg" alt="">
            </div>
        </section></div>
        <footer class="footer">
            <h3 class="is-size-4 mb-4">FashionHub</h3>
            
            {% if request.user.is_designer.is_authenticated %}
                <a href="{% url 'designer_admin' %}">Designer admin</a>
            {% else %}
                <a href="{% url 'become_designer' %}">Designer Portal</a>
            {% endif %}
                <br>
            
        </footer>

        {% block scripts %}
            
        {% endblock %}
    </body>
</html>

dbms/fashionHub/apps/designer/templates/designer/designer.html
{% extends 'core/base.html' %}

{% block title %}{{designer.name }} | {% endblock %}

{% block content %}
    <div class="columns is-multiline mb-6">
        <div class="column is-12 has-text-centered mt-6 mb-6">
            <h2 class="is-size-3">{{ designer.name }}</h2>
        </div>

        {% for product in designer.products.all %}
            {% include 'product/parts/list_item.html' %}
        {% endfor %}
    </div>
{% endblock %}

dbms/fashionHub/apps/designer/templates/designer/designer_admin.html
{% extends 'core/base.html' %}

{% block title %}Designer | {% endblock %}

{% block content %}
<div class="box">
    <h1 class="title">Designer - {{user.first_name}}</h1>

    <strong>My Balance: </strong>Rs.{{designer.get_balance}}<br>
    <strong>My paid amount: </strong>Rs.{{designer.get_paid_amount}}


    <hr>

    <a href="{% url 'edit_designer' %}" class="button is-info is-uppercase">Edit</a>
    
</div>

<div class="box">
    <h2 class="is-size-3 mb-4">My Products</h2>


    <a href="{% url 'add_product' %}" class="button is-dark is-uppercase nb-6">Add Product</a>
    <br>
    {% if products %}
        <table class="table is-fullwidth">
            <thead>
                <tr>
                    <th>Title</th>
                    <th>Price</th>
                </tr>
            </thead>

            <tbody>
                {% for product in products %}
                <tr>
                    <td>{{product.title}}</td>
                    <td>{{product.price}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>You don't have any products yet...</p>
    {% endif %}
</div>

<div class="box">
    <h2 class="is-size-3 mb-4">My orders</h2>

    {% if orders %}
        {% for order in orders %}
            <div class="{% if order.fully_paid %}has-background-success-light{% else %}has-background-info-light{% endif %} mb-2 p-4">
                <div class="columns is-multiline">
                    <div class="column is-6">
                        <h3 class="is-size-4">#{{ order.id }} - {{ order.first_name }} {{ order.last_name }}</h3>
                    </div>

                    <div class="column is-12">
                        <b>Name:</b> {{ order.first_name }} {{ order.last_name }}<br>
                        <b>Address:</b> {{ order.address }}<br>
                        <b>Zip and place:</b> {{ order.zipcode }} {{ order.place }}<br>
                        <b>E-mail:</b> {{ order.email }}<br>
                        <b>Phone:</b> {{ order.phone }}

                        <table class="table is-fullwidth mt-4">
                            <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Price</th>
                                    <th>Quantity</th>
                                    <th>Paid</th>
                                    <th>Total</th>
                                </tr>
                            </thead>

                            <tbody>
                                {% for item in order.items.all %}
                                    {% if item.designer == request.user.designer %}
                                        <tr>
                                            <td>{{ item.product.title }}</td>
                                            <td>${{ item.product.price }}</td>
                                            <td>{{ item.quantity }}</td>
                                            <td>{{ item.vendor_paid|yesno:"Yes,No" }}</td>
                                            <td>${{ item.get_total_price }}</td>
                                        </tr>
                                    {% endif %}
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% endif %}
</div>
{% endblock %}

dbms/fashionHub/apps/designer/templates/designer/designers.html
{% extends 'core/base.html' %}

{% block title %}Designers | {% endblock %}

{% block content %}
    <h1 class="title">Designers</h1>

    <div class="columns is-multiline">
        {% for id,name in designers %}
       
        <div class="column is-3">
            <div class="box">
                <h2 class="subtitle">{{name }}</h2>

                <hr>

                <a href="{% url 'designer' id %}" class="button is-dark is-uppercase">View</a>
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}

dbms/fashionHub/apps/designer/templates/designer/edit_designer.html
{% extends 'core/base.html' %}

{% block title %}Edit Designer | {% endblock %}

{% block content %}
    <h1 class="title">Edit designer</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="field">
            <label>Designer name</label>

            <div class="control">
                <input type="text" name="name" id="id_name" value="{{ designer.name }}" class="input">
            </div>

            <p class="help">This is not the same as the username!</p>
        </div>

        <div class="field">
            <label>E-mail</label>

            <div class="control">
                <input type="email" name="email" id="id_email" value="{{designer.created_by.email }}" class="input">
            </div>
        </div>

        <div class="field">
            <div class="control">
                <button class="button is-dark is-uppercase">Save changes</button>
            </div>
        </div>
    </form>
{% endblock %}

dbms/fashionHub/apps/designer/templates/designer/login.html
{% extends 'core/base.html' %}

{% block title %}Log in | {% endblock %}

{% block content %}
<h1 class="title">Log in</h1>

<form method="post" action=".">
    {% csrf_token %}

    {{form.as_p}}

    <div class="field">
        <div class="control">
            <button class="button is-dark is-uppercase">Login</button>
        </div>
    </div>
</form>
{% endblock %}